### ISSUE TITLE
Optimization required 18th DEC - yashwanth

### ISSUE THREAD

**Issue by adityagampa** [adityagampa/code-a-day#5]
![18th_dec_-_yashwanth](https://cloud.githubusercontent.com/assets/10786261/11892096/f63c09ca-a58a-11e5-8639-7aa8f835841c.png)
the question - 18 th Dec asked to consider 3 numbers.. u can fix r=8 & m=3 & n=5 but u cannot directly use the numbers '3' and '5' in the loops as those numbers may vary.. and as u have already finished the work for the day try optimizing the code.. it can be solved in O(n) only.. :) @Yashwanth18

**Comment by Yashwanth18** [comment]
optimized the code and asked user to enter the values ....thanx for pointing it :)
